/// <autosync enabled="true" />
/// <reference path="../__macosx/garage - html-css-template/source/bootstrap-3.3.6-dist/js/._bootstrap.js" />
/// <reference path="../__macosx/garage - html-css-template/source/bootstrap-3.3.6-dist/js/._jquer.1.10.js" />
/// <reference path="../__macosx/garage - html-css-template/source/bootstrap-3.3.6-dist/js/._jquery.1.11.js" />
/// <reference path="../__macosx/garage - html-css-template/source/bootstrap-3.3.6-dist/js/._jquery.js" />
/// <reference path="../__macosx/garage - html-css-template/source/bootstrap-3.3.6-dist/js/._npm.js" />
/// <reference path="../__macosx/garage - html-css-template/source/js/._isotope.js" />
/// <reference path="../__macosx/garage - html-css-template/source/js/._myscript.js" />
/// <reference path="../__macosx/garage - html-css-template/source/js/._selectordie.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery-3.1.1.js" />
/// <reference path="jquery-3.1.1.min.js" />
/// <reference path="jquery-3.1.1.slim.min.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
/// <reference path="../source/bootstrap-3.3.6-dist/js/bootstrap.js" />
/// <reference path="../source/bootstrap-3.3.6-dist/js/jquer.1.10.js" />
/// <reference path="../source/bootstrap-3.3.6-dist/js/jquery.1.11.js" />
/// <reference path="../source/bootstrap-3.3.6-dist/js/jquery.js" />
/// <reference path="../source/bootstrap-3.3.6-dist/js/npm.js" />
/// <reference path="../source/js/isotope.js" />
/// <reference path="../source/js/myscript.js" />
/// <reference path="../source/js/selectordie.js" />
