//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFiltro
    {
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public int PrecioU { get; set; }
        public System.Guid UsuarioID { get; set; }
        public int ModeloCarroID { get; set; }
        public int FabricanteCarroID { get; set; }
        public Nullable<int> MarcaProducto_IdMarca { get; set; }
        public int IdMarca { get; set; }
    }
}
